import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Roboto } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { CssBaseline, Box } from '@mui/material';
import LayoutWrapper from '@/components/LayoutWrapper';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <AppRouterCacheProvider>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <body style={{ display: 'flex', flexDirection: 'column', minHeight: '100dvh' }}>
            <LayoutWrapper>{children}</LayoutWrapper>
          </body>
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
